<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputrememberMe</name>
   <tag></tag>
   <elementGuidId>e75a749c-147d-4961-8129-e71eab9e936e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rememberMe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rememberMe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f5d811c-3c9e-4c16-90c8-8e29257bf8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8cab71cf-c6b2-43f4-9dad-81835f4f7a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rememberMe</value>
      <webElementGuid>ed95df43-95bb-42a3-bb3e-35f4f79ac548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rememberMe&quot;)</value>
      <webElementGuid>de5f6262-03bc-4f00-bd05-1af76450c86f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rememberMe']</value>
      <webElementGuid>e9778eb2-7b16-4bec-a56d-fb57cf1797af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-login']/div[3]/div/div/input</value>
      <webElementGuid>cd55a976-37bf-441d-986f-54fd33a8c1db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>a106fa3b-df0d-4b25-ac32-f942625c6a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'rememberMe']</value>
      <webElementGuid>2f9c2bb6-f854-4c25-923a-a374a5f00470</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
