<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_correctAnswer</name>
   <tag></tag>
   <elementGuidId>40a55a44-528b-4763-b130-c58172e6dff0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#correctAnswerAddA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='correctAnswerAddA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60cfce2b-6a25-484d-9d14-58533ba71ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f913c024-8ba9-445f-99cf-f00c1590c80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>correctAnswer</value>
      <webElementGuid>a7fbb934-fe24-4f28-b11a-9f7229dd9e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>correctAnswerAddA</value>
      <webElementGuid>6bd7337a-a9f7-48d7-a8a9-ff8fd21c3b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eeeb1107-e842-4870-b826-8808697e4c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;correctAnswerAddA&quot;)</value>
      <webElementGuid>48fe28e6-dc66-4164-bc51-3e3e1e8b2a2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='correctAnswerAddA']</value>
      <webElementGuid>f65ad917-7e8f-42fa-85b4-b675f209f660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[5]/div/label/input</value>
      <webElementGuid>39c34024-1922-46ee-a1d3-e906e46e2cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/label/input</value>
      <webElementGuid>c2db02a4-151d-4a2d-871b-f7075e803e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'correctAnswer' and @id = 'correctAnswerAddA']</value>
      <webElementGuid>17356afd-b308-4899-96eb-3316c35ee5cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
