<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_optB</name>
   <tag></tag>
   <elementGuidId>1d7457ed-29ab-42fd-ba37-9ac7c4b16d9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#optBAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='optBAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1e55247e-e1e2-45f6-ab95-6bed75ab675f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0e48059a-a7e3-46c8-ba96-3384d5a98578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>optB</value>
      <webElementGuid>9bd5eb31-6622-435a-9061-68c6fb314c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optBAdd</value>
      <webElementGuid>f51662a4-ce6b-4b1e-a385-9d2d606776ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8294bf2a-0052-49a9-b3df-8546839e327a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Option B</value>
      <webElementGuid>6f654a18-bc7e-4691-b440-2f47bfd94c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>6fe4cd72-ff27-49e3-b31f-e126e3d41680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optBAdd&quot;)</value>
      <webElementGuid>13a923a4-9243-44c8-9b2f-bb05708f35df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='optBAdd']</value>
      <webElementGuid>ae0ce424-b2f1-4816-8649-efb27fc05637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[3]/div[2]/div/textarea</value>
      <webElementGuid>a0b5e669-fa3e-4000-abe3-b938e1dce2c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/textarea</value>
      <webElementGuid>41a2f8e8-699e-4eb4-9a1e-a8b44400a2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'optB' and @id = 'optBAdd' and @placeholder = 'Option B']</value>
      <webElementGuid>08d05334-60a1-4a7f-ad1d-b036cae701dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
