<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_desc</name>
   <tag></tag>
   <elementGuidId>b0079519-ad35-4f4e-af0e-563568dabd3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#descAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='descAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>16fddecd-e93f-48c3-b2ef-dfa9905296cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8dd0c6ac-4624-4a2e-bcfa-b33a40c85889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>desc</value>
      <webElementGuid>8561c9f8-6625-4e89-9ccf-0618bf24f586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>descAdd</value>
      <webElementGuid>3eb4137e-1867-4cba-9a97-0a785f8b5cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b225ed4b-64fd-48f6-af1e-b23083f6bc99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>d869ab8c-5e0e-48a4-9e41-9f15cb8c609e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Question</value>
      <webElementGuid>31248823-c19c-4cd4-84c3-c922aaa158ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;descAdd&quot;)</value>
      <webElementGuid>d82e77a7-24d8-4e2a-aa9d-05f452b6a470</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='descAdd']</value>
      <webElementGuid>6060e254-d011-4a4c-b9b8-31f2f49d5767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[2]/div[2]/div/textarea</value>
      <webElementGuid>c7393f52-8c7f-4a28-8553-b5c702b1ab46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f4d5410d-06c8-4f48-bfea-1a9b84b92203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'desc' and @id = 'descAdd' and @placeholder = 'Question']</value>
      <webElementGuid>e023d52b-d8db-4579-9ce9-f5e3940cdde0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
