<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_optC</name>
   <tag></tag>
   <elementGuidId>31062382-c7a4-445a-9977-3bfe522d4442</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#optCAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='optCAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>cdd75c3f-4109-4b5f-83ec-01bc778e283a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ddd6d3ff-1121-4bc4-a91f-1a329c364f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>optC</value>
      <webElementGuid>f34b911d-8cdf-4aa6-bdd1-81d3931efc19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optCAdd</value>
      <webElementGuid>d02d5a87-1b1c-4e53-bef9-d4899e050751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7e0809d9-24bd-4ebb-8f89-43d7c42861f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Option C</value>
      <webElementGuid>9a54161d-193c-458c-9ab3-05fd59d724c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>63260360-8add-48cd-a20b-3d2385163346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optCAdd&quot;)</value>
      <webElementGuid>f3d48881-7274-4622-97b9-8b1a01b9b143</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='optCAdd']</value>
      <webElementGuid>2331356c-4551-4a9d-ba8c-c7a7926a668b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[4]/div/div/textarea</value>
      <webElementGuid>53032ccd-6c29-4804-bb9c-15c0b2c3588c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/textarea</value>
      <webElementGuid>efaee332-d0b6-45ae-af4d-99db62cdda39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'optC' and @id = 'optCAdd' and @placeholder = 'Option C']</value>
      <webElementGuid>190dc813-9f3f-40d5-af1a-3aee980d8508</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
